ekf_filter_node:  # ← 이 부분이 빠져있었음!
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false  # 2D 모드 (Z축 고정)
    print_diagnostics: true
    debug: false

    # Frame 설정
    map_frame: map
    odom_frame: odom
    base_link_frame: imure_link
    world_frame: odom

    # GPS - 위치만 사용
    odom0: /odometry/gps
    odom0_config: [true,  true,  true,   # x, y 위치만 (z 안함)
                   false, false, false,   # 자세 사용 안함 (IMU가 담당)
                   false, false, false,   # 속도 사용 안함 (EKF가 추정)
                   false, false, false,   # 각속도 사용 안함
                   false, false, false]   # 가속도 사용 안함
    odom0_differential: false
    odom0_relative: false  # GPS는 절대 좌표
    odom0_queue_size: 10

    # IMU - 자세만 사용 (가속도 제외!)
    imu0: /imure/data  # 리매핑 필요: /imure/data:=/imu/datare
    imu0_config: [false, false, false,    # 위치 사용 안함
                  true, true, true,     # yaw만 사용 (roll, pitch 끄기)
                  false, false, false,    # 선형속도 사용 안함
                  true, true, true,     # yaw 각속도만 사용
                  false, false, false]    # 가속도 사용 안함 (중요!)
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true
    imu0_queue_size: 10

    # 프로세스 노이즈
    process_noise_covariance: [
        0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
        0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
        0.0,  0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
        0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
        0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
        0.0,  0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
        0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.025,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
        0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.025,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
        0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.025,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
        0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,
        0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,
        0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,
        0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,
        0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,
        0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01]
