ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false  # 2D 모드로 z축 고정
    print_diagnostics: true
    debug: false

    # Frame 설정
    map_frame: map
    odom_frame: odom
    base_link_frame: imure_link
    world_frame: odom

    # IMU 설정 - 가속도 사용 안함!
    imu0: /imure/data  # 또는 /imu/datare로 리매핑
    imu0_config: [false, false, false,    # 위치 (사용안함)
                   true,  true,  true,     # 방향 (사용)
                   false, false, false,    # 속도 (사용안함)
                   true,  true,  true,     # 각속도 (사용)
                   false, false, false]    # 가속도 (사용안함!)
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true
    imu0_queue_size: 10
    imu0_nodelay: false

    # 프로세스 노이즈 줄이기
    process_noise_covariance: [0.005, 0.0,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,   0.005, 0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,   0.0,   0.006,  0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,   0.0,   0.0,    0.003,  0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,   0.0,   0.0,    0.0,    0.003,  0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,   0.0,   0.0,    0.0,    0.0,    0.006,  0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,   0.0,   0.0,    0.0,    0.0,    0.0,    0.0025,  0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,   0.0,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0025,  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,   0.0,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.004,  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,   0.0,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.001,  0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,   0.0,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.001,  0.0,    0.0,    0.0,    0.0,
                               0.0,   0.0,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.002,  0.0,    0.0,    0.0,
                               0.0,   0.0,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.001,  0.0,    0.0,
                               0.0,   0.0,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.001,  0.0,
                               0.0,   0.0,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0015]
