navsat_transform_node:
  ros__parameters:
    # 기본 설정
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: -0.131  # 인천 지역 자기편각
    yaw_offset: 0.0
    zero_altitude: true  # 2D 내비게이션 (고도 무시)
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: true  # EKF 방향 사용 (권장)
    wait_for_datum: false  # GPS 첫 데이터로 즉시 datum 설정

    # Transform 설정
    transform_timeout: 0.0

    # Frame IDs
    map_frame_id: map
    odom_frame_id: odom
    base_link_frame_id: imure_link  # republish한 frame_id와 일치
    utm_frame_id: utm

    # 데이터 품질 설정
    datum_service: datum

    # 추가 안정성 설정
    transform_time_offset: 0.0
